before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-transport-https
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo sh -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update -qq
  - sudo sh -c "echo exit 101 > /usr/sbin/policy-rc.d"
  - sudo chmod +x /usr/sbin/policy-rc.d

install:
  - sudo apt-get install -qq uml-utilities slirp lxc-docker tree
  - curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
  - chmod +x linux
  - mkdir -p humfs-mount/data
  - pushd humfs-mount
  - echo "Yo!" > data/hello.txt
  - humfsify $USER $USER 4G
  - popd

script:
  - ./linux quiet rootfstype=hostfs rw eth0=slirp,,$(pwd)/slirp.sh init=$(pwd)/init.sh WORKDIR=$(pwd) HOME=$(pwd)
  - netstat -l
