before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq apt-transport-https
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  - sudo sh -c "echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list"
  - sudo apt-get update -qq
  - sudo sh -c "echo exit 101 > /usr/sbin/policy-rc.d"
  - sudo chmod +x /usr/sbin/policy-rc.d

install:
  - sudo apt-get install -qq slirp lxc-docker
  - curl -sLo linux https://github.com/jpetazzo/sekexe/raw/master/uml
  - chmod +x linux
  - export DOCKER_HOST_IP="$(./get_ip)"
  - sudo ./docker_daemon $DOCKER_HOST_IP &> docker_daemon.log &
  # - tail -f -n +1 docker_daemon.log
  - ./wait_for_docker $DOCKER_HOST_IP
  - export DOCKER_HOST="tcp://$DOCKER_HOST_IP:2375"
  - docker version

script:
  - docker build .

after_failure: cat docker_daemon.log
